[desktop]
list_cmd=/usr/bin/sway-launcher-desktop list-entries
preview_cmd=/usr/bin/sway-launcher-desktop describe-desktop "{1}"
launch_cmd=/usr/bin/sway-launcher-desktop run-desktop '{1}' {2}
purge_cmd=test -f '{1}' || exit 43
