# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# terminal
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

# options
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g allow-rename off
set -g renumber-windows on
set -g history-limit 10000
set -g set-clipboard on
set -sg escape-time 0
set -g focus-events on
set -g mode-keys vi
set -g status-keys vi
set -g detach-on-destroy off

# copy mode bindings
bind k copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# navigation
bind -n S-Left previous-window
bind -n S-Right next-window
bind -n M-[ previous-window
bind -n M-] next-window

# window management
bind -n M-t new-window
bind -n M-C-[ swap-window -t -1\; select-window -t -1
bind -n M-C-] swap-window -t +1\; select-window -t +1

# resize panes
bind -n M-C-h resize-pane -L 1
bind -n M-C-j resize-pane -D 1
bind -n M-C-k resize-pane -U 1
bind -n M-C-l resize-pane -R 1

# reload config
bind r source-file ~/code/personal/dotfiles/.config/tmux/tmux.conf \; display-message "Config reloaded"

# colors
color_bg="#171B20"
color_fg="#E7EAEE"
color_text="#171B20"
color_comment="#586172"
color_session="#38FFA5"
color_right="#5CCEFF"
color_red="#F73F64"

# status bar
set -g status-position top
set -g status-style "bg=$color_bg,fg=$color_fg"
set -g status-justify left
set -g status-interval 1

# left: session name (highlights when prefix is pressed)
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[bg=$color_session fg=$color_text],#[bg=$color_right fg=$color_text]} #S "

# right: pomodoro + time
set -g status-right-length 100
set -g status-right "#{pomodoro_status} #[bg=$color_bg] #[bg=$color_right,fg=$color_text] %H:%M "

# windows
set -g window-status-separator "|" # |, │, ┃, , 
set -g window-status-format "  #W  "
set -g window-status-current-format "  #W  "
set -g window-status-current-style "fg=$color_fg,bg=$color_bg,bold"
set -g window-status-style "fg=$color_comment,bg=$color_bg"

# pane borders
set -g pane-border-style "fg=$color_comment"
set -g pane-active-border-style "fg=$color_session"

# pomodoro
set -g @pomodoro_granularity 'on'
set -g @pomodoro_on "#[bg=$color_right,fg=$color_text] "
set -g @pomodoro_complete "#[bg=$color_session,fg=$color_text] "
set -g @pomodoro_pause "#[bg=$color_red,fg=$color_text] "
set -g @pomodoro_prompt_break "#[bg=$color_comment,fg=$color_fg] begin break?"
set -g @pomodoro_prompt_pomodoro "#[bg=$color_comment,fg=$color_fg] begin work?"
set -g @pomodoro_disable_breaks "on"

# sesh
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

bind -n M-n run-shell "sesh-launch"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'olimorris/tmux-pomodoro-plus'
run '~/.tmux/plugins/tpm/tpm'
