# Sessions
[[session]]
name = "Scratch"
path = "~"

[[session]]
name = "Personal"
path = "~/notes/personal"
startup_command = "nvim"

[[session]]
name = "Work"
path = "~/notes/work"
startup_command = "nvim"

[[session]]
name = "Website"
path = "~/code/personal/astrofolio"
startup_command = "nvim"
windows = ["dev"]

[[session]]
name = "Dotfiles"
path = "~/code/personal/dotfiles"
startup_command = "nvim"

[[session]]
name = "Config"
path = "~/code/personal/dotfiles/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Base API"
path = "~/code/rework/ecomm-base"
startup_command = "nvim"

[[session]]
name = "Chard API"
path = "~/code/rework/ecomm-chard"
startup_command = "nvim"

[[session]]
name = "Chard Auth"
path = "~/code/rework/ecomm-chard-auth"
windows = ["dev", "mailhog"]

[[session]]
name = "Chard FE"
startup_command = "nvim"
path = "~/code/rework/ecomm-chard-fe"

[[session]]
name = "Jenson Samuel"
path = "~/code/rework/jensonsamuelmenswear"
startup_command = "nvim"
windows = ["tdev", "mailhog", "elasticsearch"]

[[session]]
name = "Touch Point"
path = "~/code/rework/touchpoint"
startup_command = "nvim"
windows = ["mailhog"]

[[session]]
name = "HP Source"
path = "~/code/personal/hp-source"
startup_command = "nvim"

# Windows
[[window]]
name = "dev"
startup_script = "npm run dev"

[[window]]
name = "tdev"
startup_script = "npm run theme-dev"

[[window]]
name = "mailhog"
path = "~"
startup_script = "mailhog"

[[window]]
name = "elasticsearch"
path = "~"
startup_script= "./bin/elasticsearch.sh"

